### ISSUE TITLE
GitHub Action to auto trigger build daily

### ISSUE THREAD

**Issue by AlexandraKapp** [technologiestiftung/odis-website#1]
To make the pasts events grey, the build needs to be triggered daily. 

How to set this up: https://community.netlify.com/t/scheduling-builds-and-deploys-with-netlify/2563/10

**Comment by fabianmoronzirfas** [comment]
Hooks docs

https://docs.netlify.com/configure-builds/build-hooks/

**Comment by fabianmoronzirfas** [comment]
@tori-d @Lisa-Stubert Is this still a thing?

**Comment by fabianmoronzirfas** [comment]
@julizet Let me know when you need any assistance
