### ISSUE TITLE
Markdown for italics does not seem to be working. 

### ISSUE THREAD

**Issue by tori-d** [technologiestiftung/odis-website#3]
Using * to italicize text does not seem to be working. Appears to be the case for all posts on the site. See screenshots for example

<img width="985" alt="Screen Shot 2020-02-14 at 14 55 24" src="https://user-images.githubusercontent.com/12991433/74537280-10fdfe00-4f3a-11ea-944b-b1fd2b242521.png">

![Screen Shot 2020-02-14 at 14 55 49](https://user-images.githubusercontent.com/12991433/74537311-1f4c1a00-4f3a-11ea-9c9e-4eb17a065ae2.png)

**Comment by fabianmoronzirfas** [comment]
Did you look at the source code to see if it actually generated `em` tags?
