### ISSUE TITLE
Step numbers (1., 2., etc) for the 4 steps run into description text

### ISSUE THREAD

**Issue by tori-d** [technologiestiftung/odis-website#4]
For the four steps under "Open Data erfolgreich umzusetzen ist ein mehrstufiger Prozess.
Wir begleiten Sie auf diesem Weg." on the main page, the numbers for each step (1., 2., 3., 4.) run into the text that describes that step. See screenshot for more detail.
![Screen Shot 2020-02-20 at 16 35 03](https://user-images.githubusercontent.com/12991433/74950219-13130180-53ff-11ea-9429-6bd6808c9a49.png)

**Comment by julizet** [comment]
fixed overlap with margin and width
