### ISSUE TITLE
How to better differentiate multiple resource links from each other?

### ISSUE THREAD

**Issue by tori-d** [technologiestiftung/odis-website#5]
Right now, when multiple resources are linked without a thumbnail, it's not obviously how to visually distinguish them (i.e., where does one resource end and the next one begin?). Maybe it's possible to add bullet points? Or perhaps it would help if the descriptive text were not a link but just text (and thus helps visually break up links?)?
![Screen Shot 2020-02-20 at 16 37 58](https://user-images.githubusercontent.com/12991433/74950585-9d5b6580-53ff-11ea-9511-9b08b18b1e4c.png)

**Comment by julizet** [comment]
add icons per quaetion/ressource

**Comment by julizet** [comment]
improved structure and added copy from drive document + added placeholder icon

note: copy for external ressources is still missing
